name: gomobile-android

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**/README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Docker login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}
      run: docker login https://docker.pkg.github.com -u ${username} -p ${password}
    - name: Build image
      run: docker build . -t docker.pkg.github.com/jbpratt/gomobile-android/gomobile-android:latest
    - name: Test image
      run: docker run -v $(pwd):/go/src/x/ --rm docker.pkg.github.com/jbpratt/gomobile-android/gomobile-android:latest /bin/bash -c "cd /go/src/x && gomobile init && gomobile bind -o ./sample.aar -target=android ./sample"
    - name: Publish image
      run: docker push docker.pkg.github.com/jbpratt/gomobile-android/gomobile-android:latest
